"""Text measurement for the hand-built SVG diagrams.

The flowchart used to guess node sizes (fixed 300px boxes, fixed 184x88
diamonds), which is why long labels spilled out of their shapes and rows of
three nodes overlapped. Everything here answers one question instead:
*how wide is this string, in this style, in px?* — using advance widths read
straight out of the woff2 files the page actually serves
(``font_metrics.py``, generated by ``tools/gen_font_metrics.py``).

Styles are keyed by the CSS class the renderer emits, so a font-size change in
``visuals.css`` only has to be mirrored in ``_styles`` and every size and wrap
decision follows.

A face is the set of fonts a page draws diagrams in: ``annotate`` (Bricolage
Grotesque and Monaspace Radon, the default) or ``stage`` (Geist and Geist Mono).
``with face("stage"):`` measures everything inside it in that face.
"""
from __future__ import annotations

import contextlib
import contextvars

from . import font_metrics as fm


class Style:
    """A (font table, size, line height) triple matching one CSS class."""

    __slots__ = ("table", "fallback", "size", "line_h")

    def __init__(self, table: dict[str, float], fallback: float,
                 size: float, line_h: float) -> None:
        self.table = table
        self.fallback = fallback
        self.size = size
        self.line_h = line_h


def _styles(SANS_400, SANS_600, SANS_700, MONO, MONO_FALLBACK) -> dict[str, Style]:
    # Keep in sync with the .annotate-flow and .annotate-seq rules in visuals.css.
    return {
        "flow-label":       Style(SANS_600, SANS_600["x"], 13.5, 18),
        "flow-label-error": Style(SANS_700, SANS_700["x"], 13.0, 18),
        "flow-ref":         Style(MONO, MONO_FALLBACK, 12.0, 16),
        "flow-method":      Style(MONO, MONO_FALLBACK, 11.5, 16),
        "flow-sub":         Style(SANS_400, SANS_400["x"], 11.0, 15),
        "edge-label":       Style(SANS_600, SANS_600["x"], 11.0, 14),
        # .annotate-seq — the seq-* keys are what the fixed-pitch renderer measures.
        # Labels are measured with the 600 table although the CSS sets weight 500:
        # Bricolage 500 sits between the 400 and 600 instances, so measuring with
        # 600 over-estimates by a hair and every fit decision errs toward roomy.
        "seq-name":         Style(MONO, MONO_FALLBACK, 10.0, 13),
        "seq-label":        Style(SANS_600, SANS_600["x"], 11.5, 15),
        "seq-tag":          Style(MONO, MONO_FALLBACK, 10.0, 13),
        "seq-note":         Style(MONO, MONO_FALLBACK, 10.0, 13),
        "seq-band":         Style(MONO, MONO_FALLBACK, 10.5, 14),
        "seq-legend":       Style(MONO, MONO_FALLBACK, 11.5, 15),
        # Retained: the geometry suite and older callers measure actor/arrow text
        # through these names.
        "actor-label":      Style(MONO, MONO_FALLBACK, 10.0, 13),
        "arrow-label":      Style(SANS_600, SANS_600["x"], 11.5, 15),
        "arrow-sub":        Style(MONO, MONO_FALLBACK, 10.0, 13),
    }


FACES: dict[str, dict[str, Style]] = {
    "annotate": _styles(fm.SANS_400, fm.SANS_600, fm.SANS_700, fm.MONO, fm.MONO_FALLBACK),
    "stage": _styles(fm.STAGE_SANS_400, fm.STAGE_SANS_600, fm.STAGE_SANS_700, fm.STAGE_MONO,
                     fm.STAGE_MONO_FALLBACK),
}
STYLES = FACES["annotate"]
_face: contextvars.ContextVar = contextvars.ContextVar("face", default="annotate")


@contextlib.contextmanager
def face(name: str):
    """Measure in face `name` for the length of the block."""
    if name not in FACES:
        raise ValueError(f"no face {name!r}; the faces are {', '.join(FACES)}")
    token = _face.set(name)
    try:
        yield
    finally:
        _face.reset(token)


def text_px(text: str, style: str) -> float:
    """Width of ``text`` in px when rendered in ``style``."""
    st = FACES[_face.get()][style]
    total = 0.0
    for ch in text:
        total += st.table.get(ch, st.fallback)
    return total * st.size


def line_h(style: str) -> float:
    return FACES[_face.get()][style].line_h


def wrap(text: str, style: str, max_px: float) -> list[str]:
    """Greedy word-wrap ``text`` so each line fits ``max_px``.

    Words longer than ``max_px`` are left intact on their own line — breaking
    an identifier mid-token is exactly the Mermaid behaviour this renderer
    exists to avoid. Callers size the shape from the returned lines, so an
    over-long word widens the node rather than overflowing it.
    """
    words = text.split()
    if not words:
        return [""]
    lines: list[str] = []
    cur = words[0]
    for w in words[1:]:
        cand = f"{cur} {w}"
        if text_px(cand, style) <= max_px:
            cur = cand
        else:
            lines.append(cur)
            cur = w
    lines.append(cur)
    return lines
